server:
  port: 8086
  servlet:
    context-path: /payment

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cinemeow_payment
    username: postgres
    password: sa123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    operations-sorter: method

openapi:
  service:
    api-docs: payment-service
    server: http://localhost:8086/payment
    title: Payment Service
    version: 1.0.0

app:
  services:
    booking-service: http://localhost:8085/booking

payment:
  cancel-url: https://example.com/
  return-url: https://poodle-stirring-oddly.ngrok-free.app/api/v1/payment/payments
  vnpay:
    tmn-code: ${VNPAY_TMN_CODE}
    secret-key: ${VNPAY_SECRET_KEY}
    return-url: http://localhost:5174/payment-result
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    timeout: 15 # in minutes

  paypal:
    client-id: ${PAYPAL_CLIENT_ID}
    client-secret: ${PAYPAL_CLIENT_SECRET}
    mode: sandbox